### ISSUE TITLE
A method can't be called  in HelperProtocol?

### ISSUE THREAD

**Issue by diuming** [erikberglund/SwiftPrivilegedHelper#25]
I add a function in HelperProtocol, but openFile never be called.
Could you give me advice?

```
@objc(HelperProtocol)
protocol HelperProtocol {
    func getVersion(completion: @escaping (String) -> Void)
    func openFile(completion: @escaping (UnsafeMutablePointer<FILE>?) -> Void)
}

func openFile(completion: @escaping (UnsafeMutablePointer<FILE>?) -> Void) {
        var file = fopen("/dev/auditpipe", "r")
        completion(file)
}
```

**Comment by jeff-h** [comment]
Does the compiler throw an error? 

If it seems to be silently failing, in my experience there's a good chance you're just not getting to see what's happening inside your helper, since it's a second process.

It's possible to ask Xcode to debug both processes. One method is: `Debug` > `Attach to Process by PID or Name...` and entering as the name `com.github.erikberglund.SwiftPrivilegedHelper`:

![image](https://user-images.githubusercontent.com/841871/81244876-aa373f00-9067-11ea-9113-599d9dbed631.png)

Incidentally, I am sure there'd be a way to have Xcode do this every time, instead of having to tell it via `Attach to Process by PID or Name...`. Can anyone enlighten me? :)
